import Theme from "@/constants/Theme";
import { StyleSheet } from "react-native";

/** Compact Finance Pro workspace tokens — Pulse colors, SaaS density. */
export const FinanceWs = {
  title: 15,
  page: 18,
  section: 13,
  body: 12,
  table: 11,
  meta: 10,
  label: 10,
  pill: 9,
  railWidth: 236,
  previewWidth: 380,
} as const;

export const financeInvoiceWorkspaceStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Theme.screenBackground,
  },
  appBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.surfaceBorder,
    minHeight: 40,
    backgroundColor: Theme.screenBackground,
  },
  appBarBrand: {
    fontSize: FinanceWs.title,
    fontWeight: "700",
    letterSpacing: 0.4,
    color: Theme.textPrimaryDark,
  },
  appBarMeta: {
    fontSize: FinanceWs.meta,
    fontWeight: "600",
    color: Theme.textMuted,
    marginTop: 1,
  },
  columns: {
    flex: 1,
    flexDirection: "row",
    minHeight: 0,
  },
  rail: {
    width: FinanceWs.railWidth,
    flexGrow: 0,
    flexShrink: 0,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: Theme.surfaceBorder,
    backgroundColor: Theme.screenBackground,
  },
  railHead: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 6,
  },
  railTitle: {
    fontSize: FinanceWs.label,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    color: Theme.textMuted,
  },
  railSearch: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 10,
    marginBottom: 8,
    paddingHorizontal: 8,
    height: 32,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.surfaceBorder,
    backgroundColor: Theme.surface,
  },
  railSearchInput: {
    flex: 1,
    fontSize: FinanceWs.body,
    color: Theme.textPrimary,
    paddingVertical: 0,
  },
  railRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
    borderLeftWidth: 2,
    borderLeftColor: "transparent",
  },
  railRowActive: {
    backgroundColor: Theme.surface,
    borderLeftColor: Theme.primary,
  },
  avatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: Theme.brandBlueSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: FinanceWs.meta,
    fontWeight: "700",
    color: Theme.primary,
  },
  railName: {
    fontSize: FinanceWs.body,
    fontWeight: "600",
    color: Theme.textPrimaryDark,
  },
  railMeta: {
    fontSize: FinanceWs.meta,
    color: Theme.textMuted,
    marginTop: 1,
  },
  railValue: {
    fontSize: FinanceWs.table,
    fontWeight: "600",
    color: Theme.textPrimary,
  },
  main: {
    flex: 1,
    minWidth: 0,
    backgroundColor: Theme.screenBackground,
  },
  previewCol: {
    width: FinanceWs.previewWidth,
    flexGrow: 0,
    flexShrink: 0,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: Theme.surfaceBorder,
    backgroundColor: Theme.screenBackground,
  },
  breadcrumb: {
    fontSize: FinanceWs.meta,
    color: Theme.textMuted,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  clientTitle: {
    fontSize: FinanceWs.page,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    paddingHorizontal: 12,
    marginTop: 2,
  },
  policyLine: {
    fontSize: FinanceWs.meta,
    color: Theme.textSecondary,
    paddingHorizontal: 12,
    marginTop: 2,
  },
  manualInvoiceBtn: {
    alignSelf: "flex-start",
    marginTop: 8,
    marginHorizontal: 12,
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.border,
    justifyContent: "center",
    backgroundColor: Theme.surface,
  },
  manualInvoiceBtnText: {
    fontSize: FinanceWs.body,
    fontWeight: "600",
    color: Theme.textPrimary,
  },
  podToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    marginTop: 6,
  },
  podToggle: {
    minHeight: 28,
    minWidth: 44,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.surfaceBorder,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.surface,
  },
  podToggleOn: {
    backgroundColor: Theme.brandBlue,
    borderColor: Theme.primary,
  },
  podToggleText: {
    fontSize: FinanceWs.meta,
    fontWeight: "700",
    color: Theme.textMuted,
  },
  podToggleTextOn: {
    color: Theme.buttonPrimaryText,
  },
  countLine: {
    fontSize: FinanceWs.body,
    color: Theme.textSecondary,
    paddingHorizontal: 12,
    marginTop: 4,
  },
  metrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  metric: {
    minWidth: 64,
    paddingVertical: 4,
  },
  metricValue: {
    fontSize: 15,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
  },
  metricLabel: {
    fontSize: FinanceWs.meta,
    color: Theme.textMuted,
    marginTop: 1,
  },
  tabs: {
    flexDirection: "row",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.surfaceBorder,
    paddingHorizontal: 8,
  },
  tab: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 36,
    justifyContent: "center",
  },
  tabLabel: {
    fontSize: FinanceWs.body,
    fontWeight: "600",
    color: Theme.textMuted,
  },
  tabLabelActive: {
    color: Theme.textPrimaryDark,
  },
  tabUnderline: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: 0,
    height: 2,
    backgroundColor: Theme.primary,
  },
  previewEmpty: {
    flex: 1,
    padding: 16,
    justifyContent: "center",
  },
  previewEmptyKicker: {
    fontSize: FinanceWs.label,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: Theme.textMuted,
    marginBottom: 8,
  },
  previewEmptyTitle: {
    fontSize: FinanceWs.section,
    fontWeight: "700",
    color: Theme.textPrimaryDark,
    marginBottom: 6,
  },
  previewEmptyBody: {
    fontSize: FinanceWs.body,
    color: Theme.textSecondary,
    lineHeight: 18,
  },
  pill: {
    alignSelf: "flex-start",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.surfaceBorder,
    backgroundColor: Theme.surface,
  },
  pillText: {
    fontSize: FinanceWs.pill,
    fontWeight: "700",
    letterSpacing: 0.2,
    color: Theme.textSecondary,
  },
  pillReady: {
    backgroundColor: Theme.brandBlueWashSubtle,
    borderColor: Theme.brandBlue,
  },
  pillReadyText: { color: Theme.primary },
  pillIssued: {
    backgroundColor: Theme.surface,
  },
  pillPending: {
    backgroundColor: Theme.surface,
  },
  pillBlocked: {
    backgroundColor: Theme.surface,
  },
});
